### PR TITLE
Simplify example3 😅 

### PR DESCRIPTION
**Pull request by kutyel**
This is somewhat related to #9 

If you checkout the code, the example works exactly as before.

But the previous code led me to think that explicit handling of the open dropdowns (when there are many) needs to be done, this is not true, since from the moment that you give each individual dropdown its own state, they are responsible to be closed or opened for themselves.

No one was triggering the `Toggle` event and that seemed suspicious 😅

### CODE REVIEW

**Review by PedroHLC — APPROVED** [review]
:sweat_smile:  I'll merge this one too! This was clearly wrong...

**Comment by PedroHLC** [comment]
@kutyel could you rebase this one?

**Comment by kutyel** [comment]
> @kutyel could you **rebase** this one?

Sure, done! ✅  and thanks for merging all my PRs! ❤️

**Comment by PedroHLC** [comment]
> Sure, done! white_check_mark and thanks for merging all my PRs! heart

No worries, collaborations are welcomed!


I've published it to:
https://package.elm-lang.org/packages/PaackEng/elm-ui-dropdown/1.2.0

Looks like elm packages require absolute-path for images. :sweat_smile: 

Anyway, thanks for your contribution, from PaackEng and the open-source community! :partying_face:

**Pull request merged**
