### PR TITLE
Implement a MultiSelectDropdown which auto closes on click outside 🎩

### LINKED ISSUE #9: Add OnClickOutside Event Handler
Hi people! 👋🏻 

In some complex cases working with dropdowns/selects, maybe the user wants to have a multi select thing and does not want the dropdown to close when clicking an option (we might want to click more than one). Similarly, it would make sense to "dispatch" and event `OnClickOutside` to, for example, close all the open dropdowns in the page.

Does this make sense to you?

At least I need this functionality in my use case, if it makes sense to you all also I might give it a go but I'm not 100% sure how to achieve this right now, would have to investigate 🤔

### PR DESCRIPTION
**Pull request by kutyel**
Hey people! 👋🏻 

This is a rough draft of what I need, it works but it has LOADS of duplicated code...

Maybe we could benefit from having an `Internal` module (I don't know if this pattern is a thing in Elm, in Haskell it definitely is) that shares all the common functionality.

You can check the example working in the `Example5.elm`, it works like a charm 👌🏻 

This adds the additional logic of clicking outside but maybe the logic is a big funky (you need to pass the outside handler to the outside to be used in the `subscriptions`)... feedback is welcome! 🙏🏻 

Fixes #9

### CODE REVIEW

**Comment by PedroHLC** [comment]
:sweat_smile: could you squash the top 9 commits and then rebase this branch against master? Kind of hard to review with a timeline differing from the current one.

**Comment by kutyel** [comment]
@PedroHLC done, sorry about that 😓

**Comment by PedroHLC** [comment]
:sweat_smile:  there are still some weird stuff, like `.tool-versions` and `README.md` changes that are already in the master branch.

**Comment by kutyel** [comment]
Refresh, that should not happen right now 😉

**Comment by PedroHLC** [comment]
Nope, the commit history includes a merge-commits, so it's only fixed in the GitHub reviewing, but the commit history is still dirty

**Comment by PedroHLC** [comment]
You can fix it with:
```
git reset --soft f86ef686fe317273084756f37ad99e4f515c3bf0
git commit -m "Implement a MultiSelectDropdown"
git push origin multi-select --force
```

That should do it...

**Comment by kutyel** [comment]
Done, sorry and thanks again, I hate git 😅

**Comment by PedroHLC** [comment]
That's okay :sweat_smile:  GitHub docs and most tutorials are also to blame, they don't teach the best practices on how to keep the timeline clean.

In the future, when rebase, I recommend you to use `git pull --rebase upstream master` or `git fetch upstream && git rebase upstream/master` (and avoid the GitHub button). This way, your commits are always applied over the current history/timeline instead of making some magic detours.

**Comment by kutyel** [comment]
Currently, `Dropdown.outsideTarget` needs to be passed the html `id` of the element from which we want to know that it has been clicked outside... maybe this is not perfect but I couldn't come up with a better solution 😋

**Comment by kutyel** [comment]
Actually the amount of code that changes between this module and the regular `Dropdown` is so small that maybe it will be worth just to extend the `DropdownType` and add a new `MultiSelect` flavour, + exposing the new `outsideTarget` fn which is key to solving this... @miguelcoba what are your thoughts? 😉

**Comment by kutyel** [comment]
Closing since #16 seems to be the way to go 😉  (as discussed privately with @jouderianjr)

**Pull request closed without merging**
